### ISSUE TITLE
make db.setup error

### ISSUE THREAD

**Issue by yossansr** [anonychun/skripsi-tif-uad#1]
I've already created server "role" and db "role", but it's still error when I run the make db.setup (Help me). This is the error message from the shell:

`PGPASSWORD=server psql -h localhost -p 5432 -c 'CREATE DATABASE test;' -U server
CREATE DATABASE
/Users/yossansr/Development/projects/React/skripsi-tif-uad/backend/_output/bin/server migrate
make: /Users/yossansr/Development/projects/React/skripsi-tif-uad/backend/_output/bin/server: No such file or directory
make: *** [db.migrate] Error 1`

**Comment by anonychun** [comment]
sorry for poor documentation, please run "make build" before "make db.setup"
